import type { Rubro, Conversacion } from "./types";

// Conversaciones de ejemplo por rubro para el panel /inbox.
// Datos completamente ficticios; no hay backend detrás.
const INBOX_EJEMPLO: Record<Rubro, Conversacion[]> = {
  restaurante: [
    {
      id: "1",
      cliente: "María Quispe",
      resumen: "1 Combo familiar + 2 Inca Kola 1L",
      total: 81,
      minutosAtras: 3,
      canal: "whatsapp",
      estado: "nuevo",
    },
    {
      id: "2",
      cliente: "Jorge Ramírez",
      resumen: "2 x 1/4 de pollo con papas",
      total: 36,
      minutosAtras: 12,
      canal: "instagram",
      estado: "preparacion",
    },
    {
      id: "3",
      cliente: "Lucía Fernández",
      resumen: "Pregunta por menú sin gluten",
      total: 0,
      minutosAtras: 20,
      canal: "web",
      estado: "revision",
    },
    {
      id: "4",
      cliente: "Andrés Salas",
      resumen: "1 Combo familiar (delivery a 7km)",
      total: 75,
      minutosAtras: 45,
      canal: "whatsapp",
      estado: "revision",
    },
    {
      id: "5",
      cliente: "Rosa Medina",
      resumen: "1 Ensalada fresca + 1 Inca Kola 1L",
      total: 20,
      minutosAtras: 90,
      canal: "web",
      estado: "completado",
    },
  ],
  ropa: [
    {
      id: "1",
      cliente: "Camila Torres",
      resumen: "Polo básico algodón, talla M, negro",
      total: 39.9,
      minutosAtras: 4,
      canal: "instagram",
      estado: "nuevo",
    },
    {
      id: "2",
      cliente: "Diego Paredes",
      resumen: "Jean slim fit, talla 32, azul",
      total: 89.9,
      minutosAtras: 15,
      canal: "whatsapp",
      estado: "preparacion",
    },
    {
      id: "3",
      cliente: "Valeria Ruiz",
      resumen: "Consulta: ¿tienen la casaca en talla S?",
      total: 0,
      minutosAtras: 25,
      canal: "instagram",
      estado: "revision",
    },
    {
      id: "4",
      cliente: "Sofía Cárdenas",
      resumen: "Cambio de talla fuera de plazo (10 días)",
      total: 129.9,
      minutosAtras: 60,
      canal: "web",
      estado: "revision",
    },
    {
      id: "5",
      cliente: "Martín Vega",
      resumen: "Casaca ligera, talla L, beige",
      total: 129.9,
      minutosAtras: 120,
      canal: "whatsapp",
      estado: "completado",
    },
  ],
  veterinaria: [
    {
      id: "1",
      cliente: "Patricia Núñez",
      resumen: "Consulta general para gato",
      total: 50,
      minutosAtras: 5,
      canal: "whatsapp",
      estado: "nuevo",
    },
    {
      id: "2",
      cliente: "Fernando Ríos",
      resumen: "Baño y corte para labrador",
      total: 60,
      minutosAtras: 18,
      canal: "web",
      estado: "preparacion",
    },
    {
      id: "3",
      cliente: "Gabriela Soto",
      resumen: "Emergencia: perro no come hace 2 días",
      total: 0,
      minutosAtras: 22,
      canal: "whatsapp",
      estado: "revision",
    },
    {
      id: "4",
      cliente: "Renato Aguilar",
      resumen: "Cita para vacuna hoy en 1 hora",
      total: 40,
      minutosAtras: 40,
      canal: "instagram",
      estado: "revision",
    },
    {
      id: "5",
      cliente: "Claudia Ponce",
      resumen: "Desparasitación para cachorro",
      total: 35,
      minutosAtras: 110,
      canal: "web",
      estado: "completado",
    },
  ],
  belleza: [
    {
      id: "1",
      cliente: "Alejandra Díaz",
      resumen: "Corte de cabello + peinado express",
      total: 80,
      minutosAtras: 6,
      canal: "instagram",
      estado: "nuevo",
    },
    {
      id: "2",
      cliente: "Natalia Campos",
      resumen: "Manicure clásico",
      total: 30,
      minutosAtras: 16,
      canal: "whatsapp",
      estado: "preparacion",
    },
    {
      id: "3",
      cliente: "Isabel Rojas",
      resumen: "Tinte completo, quiere reprogramar",
      total: 120,
      minutosAtras: 28,
      canal: "instagram",
      estado: "revision",
    },
    {
      id: "4",
      cliente: "Daniela Herrera",
      resumen: "Cancela cita a 2 horas del turno",
      total: 45,
      minutosAtras: 55,
      canal: "web",
      estado: "revision",
    },
    {
      id: "5",
      cliente: "Milagros León",
      resumen: "Peinado express para evento",
      total: 45,
      minutosAtras: 130,
      canal: "whatsapp",
      estado: "completado",
    },
  ],
  generico: [
    {
      id: "1",
      cliente: "Carlos Mendoza",
      resumen: "1 Producto estrella",
      total: 25,
      minutosAtras: 7,
      canal: "web",
      estado: "nuevo",
    },
    {
      id: "2",
      cliente: "Ana Flores",
      resumen: "1 Servicio premium",
      total: 80,
      minutosAtras: 19,
      canal: "whatsapp",
      estado: "preparacion",
    },
    {
      id: "3",
      cliente: "Luis Guzmán",
      resumen: "Consulta por disponibilidad de stock",
      total: 0,
      minutosAtras: 26,
      canal: "instagram",
      estado: "revision",
    },
    {
      id: "4",
      cliente: "Pamela Castro",
      resumen: "Solicita atención fuera de horario",
      total: 15,
      minutosAtras: 70,
      canal: "web",
      estado: "revision",
    },
    {
      id: "5",
      cliente: "Óscar Bravo",
      resumen: "2 Pack básico",
      total: 30,
      minutosAtras: 140,
      canal: "whatsapp",
      estado: "completado",
    },
  ],
};

export function getInboxEjemplo(rubro: Rubro): Conversacion[] {
  return INBOX_EJEMPLO[rubro].map((c) => ({ ...c }));
}
